// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/search-deals.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.1";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function unauthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated." }],
    isError: true
  };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function jsonResult(data, structured) {
  return {
    content: [{ type: "text", text: JSON.stringify(data) }],
    ...structured ? { structuredContent: structured } : {}
  };
}
var DEAL_FIELDS = "id,title,brand,category,gender_label,sale_price,original_price,discount_percent,currency,merchant,image_url,product_url,affiliate_url,is_super_deal,deal_level,promo_end_date,detected_at";

// src/lib/mcp/tools/search-deals.ts
var search_deals_default = defineTool({
  name: "search_deals",
  title: "Search deals",
  description: "Search GOLDEALS CLUB fashion, streetwear and sneaker deals by keyword, brand, category, gender, merchant, price or discount.",
  inputSchema: {
    query: z.string().optional().describe("Free-text search on the product title."),
    brand: z.string().optional().describe("Brand name, e.g. Nike, Adidas."),
    category: z.string().optional().describe("Category slug or label."),
    gender: z.string().optional().describe("Gender label, e.g. Homme, Femme, Unisexe."),
    merchant: z.string().optional().describe("Merchant/seller name, e.g. Snipes, JD Sports."),
    min_discount: z.number().optional().describe("Minimum discount percentage."),
    max_price: z.number().optional().describe("Maximum sale price."),
    super_deals_only: z.boolean().optional().describe("Only return super deals."),
    limit: z.number().optional().describe("Number of results, default 20, max 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const limit = Math.min(Math.max(Math.trunc(input.limit ?? 20), 1), 50);
    let q = supabaseForUser(ctx).from("deals").select(DEAL_FIELDS).order("display_score", { ascending: false, nullsFirst: false }).limit(limit);
    if (input.query) q = q.ilike("title", `%${input.query}%`);
    if (input.brand) q = q.ilike("brand", `%${input.brand}%`);
    if (input.category) q = q.ilike("category", `%${input.category}%`);
    if (input.gender) q = q.ilike("gender_label", `%${input.gender}%`);
    if (input.merchant) q = q.ilike("merchant", `%${input.merchant}%`);
    if (typeof input.min_discount === "number") q = q.gte("discount_percent", input.min_discount);
    if (typeof input.max_price === "number") q = q.lte("sale_price", input.max_price);
    if (input.super_deals_only) q = q.eq("is_super_deal", true);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return jsonResult(data ?? [], { deals: data ?? [], count: data?.length ?? 0 });
  }
});

// src/lib/mcp/tools/get-deal.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_deal_default = defineTool2({
  name: "get_deal",
  title: "Get deal details",
  description: "Fetch the full details of a single deal by its id, including description and purchase link.",
  inputSchema: { deal_id: z2.string().describe("The deal id returned by search_deals.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ deal_id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("deals").select("*").eq("id", deal_id).maybeSingle();
    if (error) return errorResult(error.message);
    if (!data) return errorResult(`No deal found with id ${deal_id}.`);
    return jsonResult(data, { deal: data });
  }
});

// src/lib/mcp/tools/list-favorites.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_favorites_default = defineTool3({
  name: "list_favorites",
  title: "List my favorite deals",
  description: "List the deals the signed-in user has saved as favorites on GOLDEALS CLUB.",
  inputSchema: { limit: z3.number().optional().describe("Number of favorites to return, default 50.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const max = Math.min(Math.max(Math.trunc(limit ?? 50), 1), 100);
    const supabase = supabaseForUser(ctx);
    const { data: favs, error } = await supabase.from("favorites").select("deal_id,created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(max);
    if (error) return errorResult(error.message);
    if (!favs?.length) return jsonResult([], { favorites: [], count: 0 });
    const { data: deals, error: dealsError } = await supabase.from("deals").select(DEAL_FIELDS).in("id", favs.map((f) => f.deal_id));
    if (dealsError) return errorResult(dealsError.message);
    const byId = new Map((deals ?? []).map((d) => [d.id, d]));
    const rows = favs.map((f) => ({ deal_id: f.deal_id, saved_at: f.created_at, deal: byId.get(f.deal_id) ?? null }));
    return jsonResult(rows, { favorites: rows, count: rows.length });
  }
});

// src/lib/mcp/tools/add-favorite.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
var add_favorite_default = defineTool4({
  name: "add_favorite",
  title: "Save a deal to favorites",
  description: "Save a deal to the signed-in user's GOLDEALS CLUB favorites.",
  inputSchema: { deal_id: z4.string().describe("The deal id to save.") },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ deal_id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("favorites").upsert({ user_id: ctx.getUserId(), deal_id }, { onConflict: "user_id,deal_id" }).select("deal_id,created_at");
    if (error) return errorResult(error.message);
    return jsonResult({ saved: true, deal_id }, { favorite: data?.[0] ?? { deal_id } });
  }
});

// src/lib/mcp/tools/remove-favorite.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^3.25.76";
var remove_favorite_default = defineTool5({
  name: "remove_favorite",
  title: "Remove a deal from favorites",
  description: "Remove a deal from the signed-in user's GOLDEALS CLUB favorites.",
  inputSchema: { deal_id: z5.string().describe("The deal id to remove.") },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ deal_id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { error } = await supabaseForUser(ctx).from("favorites").delete().eq("user_id", ctx.getUserId()).eq("deal_id", deal_id);
    if (error) return errorResult(error.message);
    return jsonResult({ removed: true, deal_id });
  }
});

// src/lib/mcp/index.ts
var projectRef = "yyqgxhuzobmqygksbaze";
var mcp_default = defineMcp({
  name: "goldeals-club-mcp",
  title: "GOLDEALS CLUB",
  version: "0.1.0",
  instructions: "Tools for GOLDEALS CLUB, a curated catalogue of fashion, streetwear and sneaker deals. Use `search_deals` to find current deals by brand, category, gender, merchant, price or discount, `get_deal` for full details and the purchase link, and `list_favorites` / `add_favorite` / `remove_favorite` to manage the signed-in user's saved deals.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_deals_default, get_deal_default, list_favorites_default, add_favorite_default, remove_favorite_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
